project_name: rill

release:
  prerelease: auto
  disable: true

before:
  hooks:

builds:
  # linux amd64
  - id: linux-amd64
    main: ./cli/main.go
    binary: rill
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - "-mod=readonly"
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.ShortCommit}} -X main.BuildDate={{.Date}}
blobs:
  - provider: gs
    bucket: pkg.rilldata.com
    folder: "rill/{{.Version}}"

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
    wrap_in_directory: true

checksum:
  name_template: checksums.txt

snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
