project_name: rill
release:
  prerelease: auto
before:
  hooks: null
builds:
  - id: darwin-amd64
    main: ./cli/main.go
    binary: rill
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/amd64
      - PKG_CONFIG_PATH=/sysroot/macos/amd64/usr/local/lib/pkgconfig
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - "-mod=readonly"
    ldflags:
      - >-
        -s -w -X main.Version={{.Version}} -X main.Commit={{.ShortCommit}} -X
        main.BuildDate={{.Date}}
  - id: darwin-arm64
    main: ./cli/main.go
    binary: rill
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/amd64
      - PKG_CONFIG_PATH=/sysroot/macos/amd64/usr/local/lib/pkgconfig
      - CC=oa64-clang
      - CXX=oa64-clang++
    flags:
      - "-mod=readonly"
    ldflags:
      - >-
        -s -w -X main.Version={{.Version}} -X main.Commit={{.ShortCommit}} -X
        main.BuildDate={{.Date}}
  - id: linux-amd64
    main: ./cli/main.go
    binary: rill
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
      - CGO_CFLAGS=--sysroot=/sysroot/linux/amd64
      - CGO_LDFLAGS=--sysroot=/sysroot/linux/amd64
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/linux/amd64
      - PKG_CONFIG_PATH=/sysroot/linux/amd64/usr/local/lib/pkgconfig
    flags:
      - "-mod=readonly"
    ldflags:
      - >-
        -s -w -X main.Version={{.Version}} -X main.Commit={{.ShortCommit}} -X
        main.BuildDate={{.Date}}
universal_binaries:
  - replace: true
brews:
  - homepage: "https://github.com/rilldata/homebrew-rill-developer/"
    description: "The Rill Data CLI"
    name: "rill"
    license: Apache 2.0
    tap:
      owner: rilldata
      name: homebrew-rill-developer
      branch: main
    commit_author:
      name: "rilldata"
      email: rakesh.sharma@rilldata.com
    folder: Formula
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
    wrap_in_directory: true
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
