name: release
on:
  workflow_dispatch:
  push:
    branches: [ "goreleaser-prototype" ]
    paths:
      - ".github/workflows/cli-release.yml"
      - ".goreleaser.yaml"
      - "go.mod"
      - "cli/**"
jobs:
  release:
    name: Buid w/ goreleaser
    strategy:
      matrix:
        include:
          - os: darwin
            arch: amd64
            name: macos-amd64
            ext: ""
          - os: darwin
            arch: arm64
            name: macos-arm64
            ext: ""
    runs-on: macos-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          submodules: "true"
      - name: fetch tags
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.2
      - name: Authenticate GCS
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.RILL_BINARY_SA }}"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_ACCESS_TOKEN }}
          CGO_ENABLED: 1

      # - name: release publish
      #   run: |-
      #     docker run \
      #         --rm \
      #         --privileged \
      #         -e CGO_ENABLED=1 \
      #         --env-file .release-env \
      #         -v /var/run/docker.sock:/var/run/docker.sock \
      #         -v `pwd`:/go/src/rilldata/rill-developer \
      #         -v `pwd`/sysroot:/sysroot \
      #         -v `pwd`/rill-binary-sa.json:/rill-binary-sa.json \
      #         -w /go/src/rilldata/rill-developer \
      #         goreleaser/goreleaser-cross:v1.19.2 \
      #         release --rm-dist --skip-validate
