name: release
on:
  workflow_dispatch:
  push:
    branches: ["goreleaser-prototype"]
    paths:
      - ".github/workflows/cli-release.yml"
      - ".goreleaser.yaml"
      - "go.mod"
      - "cli/**"
jobs:
  release:
    name: Upload Assets to GitHub w/ goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - run: git fetch --prune --unshallow
      - name: setup dependencies
        uses: actions/setup-go@v2
      - name: build web-local and run cli
        run: |
          ls -lrt sysroot/
#      - name: release dry run
#        run: make release-dry-run
      - name: setup release environment
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GORELEASER_ACCESS_TOKEN}}' > .release-env
      - name: release publish
        run: make release
